
spring.datasource.url=jdbc:mysql://localhost:3306/sail_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Carlinhos12-
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true